line-length = 80
target-version = "py311"
exclude = [
    ".git",
    "__pycache__",
    "venv",
    ".venv",
    "env",
    ".env",
    "migrations"
]

[lint]
select = [
    "E",
    "E501", # line too long
    "F",
    "I",
    "B",
    "UP",
]

[lint.isort]
known-first-party = ["app"]
combine-as-imports = true
force-single-line = false

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
