name: Commitlint

on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - name: Lint PR title
        uses: marocchino/commitlint-action
        with:
          configFile: .commitlintrc.json
